name: Initialize Exercise 3

on: 
  push:
    branches:
    - main

jobs:
  build:
    name: FM4SE-Exercise-3 | SMT Solving
    runs-on: ubuntu-latest
    if: github.actor == 'github-classroom[bot]'
    steps:
      - name: Checkout Starter Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Initialize Exercise
        run: |
          chmod +x gradlew
          ./gradlew generatePuzzle
      
      - name: Commit Puzzle 
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add 'puzzle.md'
          git add 'README.md'
          git commit -m "Puzzle generated" || exit 0
          git push -f origin main
